### ISSUE TITLE
No support for OSX?

### ISSUE THREAD

**Issue by twiecki** [aseyboldt/nutpie#1]
```
📦 Built wheel for CPython 3.8 to /var/folders/mn/0x4pxw0n61lf479ndp07r0gr0000gn/T/.tmpexAgcH/nutpie-0.1.0-cp38-cp38-macosx_10_7_x86_64.whl
💥 maturin failed
  Caused by: pip install in /Users/twiecki/miniforge3/envs/psiturk failed running ["-m", "pip", "--disable-pip-version-check", "install", "--force-reinstall"]: exit status: 1
--- Stdout:

--- Stderr:
ERROR: nutpie-0.1.0-cp38-cp38-macosx_10_7_x86_64.whl is not a supported wheel on this platform.
```

**Comment by aseyboldt** [comment]
This is on the M1, right?
Looks like it might be this issue? https://github.com/PyO3/maturin/issues/757

**Comment by twiecki** [comment]
Yes, M1. But looks like it's fixed there?

**Comment by aseyboldt** [comment]
I think this might be a bug somewhere in something that set up the environment.
`maturin` compiled the wheel for `x86_64` for some reason, probably because python told it to. If this is in fact the case, the output of 
```
❯ python -c 'import sysconfig; print(sysconfig.get_platform())'
```
would be `macosx-10.7-x86_64`. (is it?)

It should be `macosx-${some_version}-arm64`, so that maturin knows to build it for arm64.

**Comment by twiecki** [comment]
I cleaned things up a bit but still getting the same error :-/. Now have `maturin` installed in conda-forge. `macosx-11.0-arm64` gets returned.  Weird...

**Comment by twiecki** [comment]
Oh, but something is definitely wrong, because the wheel still says `ERROR: nutpie-0.1.0-cp39-cp39-macosx_10_7_x86_64.whl is not a supported wheel on this platform.`.

**Comment by twiecki** [comment]
Fixed by reinstalling homebrew and then rust.
